name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Switch Docker to Windows containers
      run: |
        # Switch Docker to Windows containers
        & "C:\Program Files\Docker\Docker\DockerCli.exe" -SwitchDaemon

    - name: Ensure Docker is using Windows containers
      run: |
        # Check if Docker is using Windows containers
        $dockerInfo = docker info --format "{{.OSType}}"
        if ($dockerInfo -ne "windows") {
          Write-Host "Docker is not using Windows containers. This should not happen on a Windows runner."
          exit 1
        }

    - name: Build Docker image
      run: |
        $timestamp = Get-Date -Format "yyyyMMddHHmmss"
        $imageTag = "ghcr.io/${{ github.repository }}/qt550-mingw492-cmake-nuget:$timestamp"
        $latestTag = "ghcr.io/${{ github.repository }}/qt550-mingw492-cmake-nuget:latest"
        docker build -t $imageTag -t $latestTag .

    - name: Push Docker image
      run: |
        $timestamp = Get-Date -Format "yyyyMMddHHmmss"
        $imageTag = "ghcr.io/${{ github.repository }}/qt550-mingw492-cmake-nuget:$timestamp"
        $latestTag = "ghcr.io/${{ github.repository }}/qt550-mingw492-cmake-nuget:latest"
        docker push $imageTag
        docker push $latestTag
